name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint Action step
        uses: timkinsman/eslint-action@master
        #with:
          #autofixes: true
      